branch-defaults:
  develop:
    environment: simpletix-dev
  main:
    environment: simpletix-prod

global:
  application_name: simpletix
  default_region: us-east-1
  default_ec2_keyname: simpletix
  default_platform: Python 3.13 running on 64bit Amazon Linux 2023
  include_git_submodules: true
  profile: null
  sc: git
  workspace_type: Application
