# .travis.yml
dist: focal
language: python
python: "3.12"

services:
  - postgresql

addons:
  postgresql: "14"

env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings
    - PYTHONWARNINGS=ignore
    - POSTGRES_DB=simpletix
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=  # can be empty for CI

before_install:
  - cd simpletix

install:
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt

before_script:
  # Create DB and run migrations
  - psql -c "CREATE DATABASE $POSTGRES_DB;" -U $POSTGRES_USER
  - python manage.py migrate --noinput

script:
  - black --check .
  - flake8 .
  - pytest

after_success:
  - coveralls
